import {
  Box,
  Button,
  Container,
  Heading,
  HStack,
  Input,
  InputGroup,
  InputLeftElement,
  Spacer,
} from '@chakra-ui/react';
import Head from 'next/head';
import { MagnifyingGlass, Plus } from 'phosphor-react';

import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Contract Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main" bg="gray.100" h="100vh">
        <Navbar />
        <Container maxW="container.xl" mt={6}>
          <HStack spacing={4}>
            <Heading>Contracts</Heading>
            <Spacer />
            <InputGroup variant="filled" colorScheme="cyan" maxW="200px">
              <InputLeftElement pointerEvents="none">
                <MagnifyingGlass />
              </InputLeftElement>
              <Input placeholder="Search" />
            </InputGroup>
            <Button leftIcon={<Plus />} colorScheme="teal">
              Create Contract
            </Button>
          </HStack>
        </Container>
      </Box>
    </>
  );
}
